### ISSUE TITLE
Normal text formatting

### ISSUE THREAD

**Issue by phenotypic** [smastrom/headless-gatsby-multilang#13]
Hi there, thank you very much for making this project. It looks excellent and is very easy to set up.

I'm struggling with some basic text formatting though. When editing or creating new `Other pages` I am able to use the three built-in blocks easily, but when I wan to write normal text, it always appears too far to the left. Trying the same thing in the `Blog` section works without a problem.

Please see this example:

Text editor (Other pages):

<img width="790" alt="Screenshot 2022-04-21 at 22 33 03" src="https://user-images.githubusercontent.com/33377034/164470570-f11aa6b9-f497-4ec3-891d-2689001874d6.png">

Web page:

<img width="1440" alt="Screenshot 2022-04-21 at 22 33 34" src="https://user-images.githubusercontent.com/33377034/164470639-0bc9e221-1afa-476c-9dbb-e4269156cee6.png">

Is this a bug or am I formatting the text incorrectly? Thank you in advance for your help!

**Comment by smastrom** [comment]
Hi @phenotypic, this is completely normal. The content model **Other Pages**, (the one you're editing) is rendered by the the template **OtherPage.jsx** which currently is configured to render out-of-the-box those blocks:

- Hero
- Three Features Sets
- Section - Image Right
- Section - Image Left

When adding some content you should first:
1. Select the block you want to render the content into (typing "/" as shortcut):
![Schermata 2022-04-21 alle 15 56 32](https://user-images.githubusercontent.com/78644132/164474128-9f321204-9659-4d6f-b035-ad5978df281f.png)
2. Add the content to the block:
![Schermata 2022-04-21 alle 15 58 01](https://user-images.githubusercontent.com/78644132/164474249-0d07063e-497f-420a-83de-bf98cce3adee.png)
3. Then see the block rendered as a section in the page:
![Schermata 2022-04-21 alle 16 00 23](https://user-images.githubusercontent.com/78644132/164474682-d61738c8-1ee2-4b73-9c3a-f7bdfb6bffcb.png)

By adding some arbitrary text in the StructuredText without selecting a block first will result in some vanilla HTML rendered without using any component.

**Comment by smastrom** [comment]
This is completely possible but you will have to edit the **OtherPages.jsx** template file. First you have to create a new block (e.g. "Section Without Image") set the fields you want into it (like just a Structured Text Field for your specific case) and configure the `strucutredBody` field to accept data from the block you just created:

![Schermata 2022-04-21 alle 16 39 13](https://user-images.githubusercontent.com/78644132/164482949-19849274-7fd9-4113-8b25-2f7f9d1d4244.png)

Navigate to the record, add the block, add the text content and then tell the template how to render it.

As far as I can tell, you can create a new section with the following CSS code:

```css
.sectionClassName {
  width: 100%;
  max-width: var(--globalContainer);
  margin: auto;
  padding: var(--globalPaddingTb) var(--globalPaddingLr);
}
```

Query in the `structuredBody` field the fragment of the newly created block, you can use GraphiQL explorer to be sure the nodes are correct. (No that text is the fieldId of the StructuredText field contained in your block):

```js
      ... on DatoCmsSectionWithoutImage {
        __typename
        id: originalId
        text {
          value
          links {
            ... on DatoCmsOtherPage {
              id: originalId
            }
            ... on DatoCmsHomepage {
              id: originalId
            }
          }
        }
      }
```
Then add a new case clause and render everything:

```jsx
      case 'DatoCmsSectionWithoutImage':
        return (
          <section className="sectionClassName">
               <RichText>
                  <StructuredText
                    data={text}
                    renderLinkToRecord={({
                      record: { id },
                      children,
                      transformedMeta,
                    }) => (
                      <Navigator {...transformedMeta} recordId={id}>
                        {children}
                      </Navigator>
                    )}
                  />
             </RichText>
          </section>
        );
```

**Comment by phenotypic** [comment]
Thanks for getting back to me. I've been able to follow most of the steps you listed, but I'm not sure which file to place the CSS code into?

Also, would it be possible for you to integrate this feature into the main project as a default for text in `Other Pages`, like it is for the `Blog` sections? I think it's a feature a lot of people would appreciate it.

Thank you again for all of your work :)

**Comment by smastrom** [comment]
Hi @phenotypic I wrote that CSS just to show you how to center the section which will host the block you're going to render. You have different ways depending on how you prefer to include CSS, it is totally up to you. If you wish to use vanilla CSS, you can create a CSS file, declare the class (as displayed above), import that CSS file (like `import "../yourcssstylefile.css"`) in the OtherPages.jsx template and assign the class to the `<section>` element.

If you like the styled-components approach (same of the starter), just create a new component like:

```js
import styled from "styled-components";

export const Section = styled.section`
  width: 100%;
  max-width: var(--globalContainer);
  margin: auto;
  padding: var(--globalPaddingTb) var(--globalPaddingLr);
` 
```

Then import that component in **OtherPages.jsx** and use it as a container:

```js
import { Section } from "../../yourPath"
      
      ...
      case 'DatoCmsSectionWithoutImage':
        return (
          <Section>
               <RichText>
                  <StructuredText
                    data={text}
                    renderLinkToRecord={({
                      record: { id },
                      children,
                      transformedMeta,
                    }) => (
                      <Navigator {...transformedMeta} recordId={id}>
                        {children}
                      </Navigator>
                    )}
                  />
             </RichText>
          </Section>
        );
```

Also, the starter has different ready-made sections components you can use, just check `Layout/sharedStyles/sectionStyles.js`. There's already a `<Section />` component you can use that should fit your needs. However by creating yourself the style / styled-component you will have more control on customization as such component has been already used to host the Article page.

Regarding your suggestion, I will keep it in mind when I will release a new version. Thank you!

**Comment by phenotypic** [comment]
That's very helpful, thank you for providing more detailed instructions.

I've been able to achieve the desired formatting using the code you provided. Thanks again for your help!
